### ISSUE TITLE
Field Type not showing

### ISSUE THREAD

**Issue by jeffceriello** [taylormsj/acf-cf7#12]
Hi Taylor,

I can't get the Contact Form 7 Field Type to show. I've added and activated the plugin, what else should I do?

Thank you,
Jeff

![screen shot 2017-11-09 at 19 13 59](https://user-images.githubusercontent.com/5859601/32622164-511bb5f2-c582-11e7-88ab-e48de6d9e0ab.png)

**Comment by jeffceriello** [comment]
For whoever downloaded the plugin from the wordpress.org directory, that one is outdated. It doesn't have support for ACF v5+.

**You should download it from GitHub**

**Comment by qm2k** [comment]
Was also bitten by this. Is there a reason WordPress directory still has outdated version?
